apiVersion: v1
kind: Service
metadata:
  labels:
    name: westernwall-etcd
  name: westernwall-etcd
spec:
  ports:
    - name: serverport
      port: 2379
      targetPort: 2379
    - name: clientport
      port: 4001
      targetPort: 4001
  selector:
    name: westernwall-etcd
