apiVersion: v1
kind: Service
metadata:
  name: mongo-3
  labels:
    name: mongo-3
spec:
  type: NodePort
  ports:
    - name: mongo-port
      port: 27017
      targetPort: 27017
      nodePort: 31003
  selector:
    name: mongo-3
