kind: "DeploymentConfig"
apiVersion: "v1"
metadata:
  name: "mongo-3"
spec:
  template:
    metadata:
      labels:
        name: "mongo-3"
        app: "mongo"
    spec:
      containers:
        - name: "mongo"
          image: "westernwall/mongo:latest"
          ports:
            - name: mongo-port
              containerPort: 27017
              protocol: "TCP"
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "100m"
              memory: "100Mi"
          command:
            - "/bin/sh"
            - "-ec"
            - |
              sleep 30
              mongod --bind_ip_all --replSet rs0
          volumeMounts:
          - name: datadir
            mountPath: /data/db
      volumes:
        - name: datadir
          persistentVolumeClaim:
            claimName: mongo-3
  replicas: 1
  triggers:
    - type: "ConfigChange"
    - type: "ImageChange"
      imageChangeParams:
        automatic: true
        containerNames:
          - "mongo"
        from:
          kind: "ImageStreamTag"
          name: "mongo:latest"
  strategy:
    type: "Recreate"
  revisionHistoryLimit: 2
  minReadySeconds: 0
