apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: status-mongo-db
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            parent: "mongo:latest"
        spec:
          containers:
          - name: "mongo"
            image: "mongo:latest"
            command:
              - "/bin/sh"
              - "-ec"
              - |
                mongo mongo-client:27017 rs.status()"
          restartPolicy: OnFailure