apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: status-mongo-db
spec:
  schedule: "*/10 * * * *"
  successfulJobsHistoryLimit: 3 
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            parent: "status-mongo-db"
        spec:
          containers:
          - name: "mongo"
            image: "docker-registry.default.svc:5000/westernwall/mongo:latest"
            resources:
              requests:
                cpu: "100m"
                memory: "100Mi"
              limits:
                cpu: "100m"
                memory: "100Mi"
            command:
              - "/bin/sh"
              - "-ec"
              - |
                mongo mongo-client:27017 --eval 'rs.status()'
          restartPolicy: Never
