apiVersion: batch/v1
kind: Job
metadata:
  name: initiate-mongo-db
spec:
  parallelism: 1
  completions: 1
  template:
    metadata:
      name: initiate-mongo-db
    spec:
      containers:
      - name: "mongo"
        image: "mongo:latest"
        command:
          - "/bin/sh"
          - "-ec"
          - |
            mongo mongo-client:27017 rs.initiate({_id : "rs0", members: [{ _id: 0, host: "ocp-ports.nithralas.local:30017" },{ _id: 1, host: "ocp-ports.nithralas.local:30018" },{ _id: 2, host: "ocp-ports.nithralas.local:30019" }]})"
      restartPolicy: OnFailure