kind: NetworkPolicy
apiVersion: extensions/v1beta1
metadata:
  name: allow-http
  namespace: westernwall
spec:
 podSelector:
   matchLabels:
     role: web
 ingress:
 - from: 
   - podSelector: {}
   - namespaceSelector: {}
- ports:
  - protocol: TCP
    port: 5000
