apiVersion: v1
kind: PersistentVolume
metadata:
  name: westernwall-etcd-pvol
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /localstorage/westernwalletcd
    server: 10.0.0.15
