apiVersion: v1
kind: Service
metadata:
  name: mongo-2
  labels:
    name: mongo-2
spec:
  type: NodePort
  ports:
    - name: mongo-port
      port: 27017
      targetPort: 27017
      nodePort: 30018
  selector:
    name: mongo-2