apiVersion: v1
kind: Service
metadata:
  name: mongo-1
  labels:
    name: mongo-1
spec:
  type: NodePort
  ports:
    - name: mongo-port
      port: 27017
      targetPort: 27017
      nodePort: 30017
  selector:
    name: mongo-1
